language: php
php:
  - "7.2"
  - "7.3"
  - "7.4snapshot"
  - "nightly"
env:
  - SYMFONY_VERSION=4.4
  - SYMFONY_VERSION=dev-master
install:
  - "composer require symfony/property-info:${SYMFONY_VERSION} --no-update --ignore-platform-reqs"
  - "composer install --ignore-platform-reqs"
jobs:
  allow_failures:
    - php: nightly
    - env: "SYMFONY_VERSION=dev-master"

